"""Golden snapshot of pure-math outputs — Step 0 of the quant refactor.

Frozen from pre-refactor run_picks.py / sgp_builder.py. Each function is imported
from its public location; extract-and-re-export keeps those imports valid after
Steps 1-6 move the implementations into engine/quant/. Any numeric drift in a moved
function breaks these exact-equality assertions. Generated by _gen_golden.py."""
import math

import run_picks as rp
import sgp_builder as sgp


RP_GOLDEN = {
    "poisson_pmf": [
        ((0, 2.0), 0.1353352832366127),
        ((1, 2.0), 0.2706705664732254),
        ((3, 2.0), 0.1804470443154836),
        ((5, 5.0), 0.1754673697678507),
        ((0, 0.0), 1.0),
        ((2, 0.0), 0.0),
    ],
    "poisson_cdf": [
        ((0, 2.0), 0.1353352832366127),
        ((2, 2.0), 0.6766764161830635),
        ((5, 5.0), 0.6159606548330632),
        ((3, 0.0), 1.0),
    ],
    "normal_cdf": [
        ((25.0, 25.0, 5.0), 0.5),
        ((20.0, 25.0, 5.0), 0.15865525393145713),
        ((30.0, 25.0, 5.0), 0.8413447460685428),
        ((5.0, 3.0, 0.0), 1.0),
    ],
    "negbinom_pmf": [
        ((0, 5.0, 9.15), 0.018517467282202698),
        ((3, 5.0, 9.15), 0.1410045194263115),
        ((10, 12.0, 14.7), 0.0871374672596539),
        ((0, 0.0, 5.0), 1.0),
        ((-1, 5.0, 9.15), 0.0),
    ],
    "negbinom_cdf": [
        ((3, 5.0, 9.15), 0.32675872291725466),
        ((10, 12.0, 14.7), 0.40680169044118486),
        ((0, 0.0, 5.0), 1.0),
    ],
    "implied_prob": [
        ((-200,), 0.6666666666666666),
        ((-110,), 0.5238095238095238),
        ((100,), 0.5),
        ((150,), 0.4),
        ((0,), 0.0),
    ],
    "no_vig": [
        ((0.55, 0.55), (0.5, 0.5)),
        ((0.6, 0.45), (0.5714285714285714, 0.42857142857142855)),
        ((0.0, 0.0), (0.5, 0.5)),
    ],
    "prob_to_american": [
        ((0.3,), 233.33333333333334),
        ((0.5,), -100.0),
        ((0.6,), -149.99999999999997),
        ((0.524,), -110.08403361344538),
    ],
    "is_decimal_leak": [
        ((1.91,), True),
        ((2.6,), False),
        ((0.5,), False),
        ((2.0,), True),
    ],
    "mlb_ml_from_nb": [
        ((4.5, 4.5, 3.548), 0.4999957565822658),
        ((5.0, 4.0, 3.548), 0.5841476658227599),
        ((0.0, 4.0, 3.548), 0.5),
    ],
    "calc_tb_prob": [
        ((1.0, 0.4, 0.05, 0.3, 1.5), (0.6524509873299629, 0.3475490126700371)),
        ((0.8, 0.3, 0.02, 0.2, 2.5), (0.3535323885983904, 0.6464676114016096)),
    ],
    "calc_edge": [
        ((0.55, -110, -110), (0.050000000000000044, -0.050000000000000044, 0.5, 0.5)),
        ((0.6, -120, 100), (0.07826086956521738, -0.07826086956521738, 0.5217391304347826, 0.4782608695652174)),
    ],
}

SGP_GOLDEN = {
    "_probit": [
        ((0.5,), 0.0),
        ((0.75,), 0.6744897496907685),
        ((0.99,), 2.3263478739444947),
        ((0.01,), -2.3263478739444947),
    ],
    "_copula_joint_approx": [
        (((0.68, 0.7, 0.66), 0.2), 0.33349536),
        (((0.68, 0.7), 0.35), 0.476238),
    ],
    "_american_to_decimal": [
        ((-110,), 1.9090909090909092),
        ((150,), 2.5),
        ((-200,), 1.5),
    ],
    "_decimal_to_american": [
        ((1.909,), -110),
        ((2.5,), 150),
        ((1.5,), -200),
    ],
}


def test_run_picks_pure_math_golden():
    for name, cases in RP_GOLDEN.items():
        fn = getattr(rp, name)
        for args, expected in cases:
            assert fn(*args) == expected, f'{name}{args}: {fn(*args)!r} != {expected!r}'


def test_sgp_pure_math_golden():
    for name, cases in SGP_GOLDEN.items():
        fn = getattr(sgp, name)
        for args, expected in cases:
            assert fn(*args) == expected, f'{name}{args}: {fn(*args)!r} != {expected!r}'


def test_cholesky_golden():
    assert sgp._cholesky([[1.0, 0.3], [0.3, 1.0]]) == [[1.0, 0.0], [0.3, 0.9539392014169457]]


def test_copula_joint_prob_deterministic_golden():
    # Seeded MC (random.Random(seed)) — deterministic across runs/machines.
    assert sgp._copula_joint_prob([0.68, 0.7], [[1.0, 0.35], [0.35, 1.0]], n_samples=200, seed=42) == 0.46
    assert sgp._copula_joint_prob([0.68, 0.7, 0.66], [[1.0, 0.3, 0.2], [0.3, 1.0, 0.15], [0.2, 0.15, 1.0]], n_samples=200, seed=42) == 0.37


def test_copula_module_matches_sgp_reexport():
    # quant.copula is the canonical home; sgp_builder re-exports the underscore
    # aliases. Both paths must be bit-identical for the same inputs/seed.
    from quant import copula
    assert copula.probit(0.75) == sgp._probit(0.75) == 0.6744897496907685
    assert copula.cholesky([[1.0, 0.3], [0.3, 1.0]]) == sgp._cholesky([[1.0, 0.3], [0.3, 1.0]])
    assert copula.copula_joint_approx((0.68, 0.7), 0.35) == sgp._copula_joint_approx((0.68, 0.7), 0.35) == 0.476238
    assert copula.copula_joint_prob([0.68, 0.7], [[1.0, 0.35], [0.35, 1.0]], n_samples=200, seed=42) == 0.46


def test_implied_prob_or_none_matches_canonical_for_valid_odds():
    """P0.6: capture_clv/clv_report now consume implied_prob_or_none. For valid
    odds it must equal the bare canonical (formula is single-sourced)."""
    from quant.odds import implied_prob, implied_prob_or_none
    for o in (-200, -110, 100, 150, -101, 250, "-110", "150"):
        assert implied_prob_or_none(o) == implied_prob(float(o))


def test_implied_prob_or_none_c6_guard():
    """P0.6: preserves the C6 contract the deleted forks had — None for 0, NaN,
    inf, and non-numeric, so the CLV path skips corrupt rows (canonical returns
    0.0 for 0 and would crash on non-numeric)."""
    from quant.odds import implied_prob_or_none
    assert implied_prob_or_none(0) is None
    assert implied_prob_or_none(float("nan")) is None
    assert implied_prob_or_none(float("inf")) is None
    assert implied_prob_or_none("not-a-number") is None
    assert implied_prob_or_none(None) is None


def test_clv_modules_use_canonical_implied_prob():
    """P0.6: both CLV modules must reference the canonical hardened function,
    not a local fork."""
    import capture_clv
    import clv_report
    from quant.odds import implied_prob_or_none
    assert capture_clv.implied_prob is implied_prob_or_none
    assert clv_report.implied_prob is implied_prob_or_none
